### ISSUE TITLE
random_person_with_initial and random_people_with_different_initials functions

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-extension-random-person#2]
Some people like to give characters names starting with a particular letter, so they can be referred to later by just that letter.

There are two ways to solve this:

* pick a random name starting a given letter. This would lead to overuse of names starting A, B, C, but lets you avoid things like O, which is easily confused with zero or used for the origin point.
* pick a set of random names, each with distinct initials. It could take an optional argument of letters not to use.

**Comment by jhoobergs** [comment]
I think this is already resolved?

**Comment by christianp** [comment]
So it is!
